export const members = [
  {
    id: '1',
    name: 'Christian Nwamba',
    handle: '@christian',
    email: 'Sengkang',
    avatarUrl: 'https://bit.ly/code-beast',
    status: '1',
    role: 'Anchorvale',
    rating: 40,
  },
  {
    id: '2',
    name: 'Kent C. Dodds',
    handle: '@kent',
    email: 'Jurong East',
    avatarUrl: 'https://bit.ly/kent-c-dodds',
    status: '2',
    role: 'Avenue 10',
    rating: 38,
  },
  {
    id: '3',
    name: 'Prosper Otemuyiwa',
    handle: '@prosper',
    email: 'Macpherson',
    avatarUrl: 'https://bit.ly/prosper-baba',
    status: '3',
    role: 'Street 8',
    rating: 35,
  },
  {
    id: '4',
    name: 'Ryan Florence',
    handle: '@ryan',
    email: 'Lavender',
    avatarUrl: 'https://bit.ly/ryan-florence',
    status: '4',
    role: 'Center',
    rating: 30,
  },
  {
    id: '5',
    name: 'Segun Adebayo',
    handle: '@segun',
    email: 'Tampines',
    avatarUrl: 'https://bit.ly/sage-adebayo',
    status: '5',
    role: 'West',
    rating: 29,
  },
]
